version: '3'
services:
  cavin-huang-note:
    build:
      context: .
      dockerfile: Dockerfile
    image: cavin-huang-note # 引用官网 nginx 镜像
    container_name: cavin-huang-note
    ports:
      - 8085:5000 # 宿主机可以用 127.0.0.1:8085 即可连接容器中的数据库